### ISSUE TITLE
Local function find_references() failure 

### ISSUE THREAD

**Issue by ayushkr19** [emmanueltouzery/code-compass.nvim#3]
Hi, first of all, fantastic work with this plugin. It really makes navigating codebases without a Java LSP super easy :)

I'm facing an issue with finding reference for a function which is only used once in the file. 

Repro-
```
public class Main {

    public static void main() {
        func();
        func(); // Delete this line to reproduce
    }

    private void func() {
        System.out.println("Hello");
    }
}

```

leads to a stack trace 

```
Error executing vim.schedule lua callback: ...-compass.nvim/lua/code_compass/code_compass_get_refs.lua:9: attempt to call global 'find_buf_for_fname' (a nil value)
stack traceback:
	...-compass.nvim/lua/code_compass/code_compass_get_refs.lua:9: in function 'picker_finish'
	...-compass.nvim/lua/code_compass/code_compass_get_refs.lua:103: in function 'run_finish'
	...nvim/lazy/code-compass.nvim/lua/code_compass/helpers.lua:80: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

```

Haven't been able to test with a clean neovim, let me know if you're unable to reproduce.
I can look into raising a PR for this weekend (provided you're up for it), I haven't looked at the code yet, but am not that familiar with Lua yet.

**Comment by emmanueltouzery** [comment]
yes, good catch! stupid mistake from me as I had that function defined as global in my config too, that's the reason I didn't catch it.
